name: PHP Code Sniffer

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install
    - name: vendor/bin/phpcs /index.php --standard=PSR2
      run: vendor/bin/phpcs
    - name: Run PHPCBF
      run: vendor/bin/phpcbf
