name: PHPCS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install PHPCS
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Run PHPCS
        run: phpcs --standard=PSR2 /workflows
